import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import Header from "../components/header";
import Sidebar from "../components/sidebar";
import Footer from "../components/footer";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session) redirect("/login");

  return (
    <html lang="en">
      <body className="max-h-screen">
        <Header />
        <div className="flex">
          <Sidebar />
          <div className="p-12">{children}</div>
        </div>
        <div className="">
          <Footer />
        </div>
      </body>
    </html>
  );
}
